const characterIcons = [
    {name: "Captain Olimar", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/olimar.png")}, 
    {name: "Louie", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/louie.png")}, 
    {name: "Oatchi", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/oatchi.png")}, 
    {name: "Shepherd", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/shepherd.png")}, 
    {name: "Collin", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/collin.png")}, 
    {name: "Russ", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/russ.png")}, 
    {name: "Dingo", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/dingo.png")}, 
    {name: "Yonny", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/yonny.png")}, 
    {name: "Bernard", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/bernard.png")},
    // {name: "Schnauz", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/schnauz.png")}, 
    // {name: "Dalmo", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/dalmo.png")}, 
    // {name: "Kingsly", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/kingsly.png")}, 
    // {name: "Francois", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/francois.png")}, 
    // {name: "Pitunia", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/pitunia.png")}, 
    // {name: "Puddle", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/puddle.png")}, 
    // {name: "Mika", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/mika.png")}, 
    // {name: "Sy", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/sy.png")}, 
    // {name: "Dash", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/dash.png")},
    // {name: "Corgwin", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/corgwin.png")},
    // {name: "Jin", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/jin.png")},
    // {name: "Chet", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/chet.png")},
    // {name: "Sheeba", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/sheeba.png")},
    // {name: "Muggs", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/muggs.png")},
    // {name: "Keesh", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/keesh.png")},
    // {name: "Osa", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/osa.png")},
    // {name: "Frise", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/frise.png")},
    // {name: "Kaia", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/kaia.png")},
    // {name: "Vonda", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/vonda.png")},
    // {name: "Patch", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/patch.png")},
    // {name: "Chewy", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/chewy.png")},
    // {name: "Twyla", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/twyla.png")},
    // {name: "Don Bergman", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/don_bergman.png")},
    // {name: "Bernise", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/bernise.png")},
    // {name: "Yorke", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/yorke.png")},
    // {name: "Horatio", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/horatio.png")},
    // {name: "Nelle", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/nelle.png")},
    // {name: "Molly", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/molly.png")},
    // {name: "Santi", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/santi.png")},
    // {name: "Kayz", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/kayz.png")},
    // {name: "Kit", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/kit.png")},
    // {name: "Komo", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/komo.png")},
    // {name: "Alpin", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/alphin.png")},
    // {name: "Chowder", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/chowder.png")},
    // {name: "Lapi", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/lapi.png")},
    // {name: "Sammy", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/sammy.png")},
    // {name: "Wolfgang", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/wolfgang.png")},
    // {name: "Ren", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/ren.png")},
    // {name: "Boris", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/boris.png")},
    // {name: "Grace", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/grace.png")},
    // {name: "Fawks", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/fawks.png")},
    // {name: "Beaux", image: require("/home/jesseilc123/development/code/phase-5/Phase-5-capstone-project/client/src/utils/character_images/beaux.png")},
]

export default characterIcons;