"""Added validation to user, posts, and replies

Revision ID: 532815d25eb1
Revises: c273e20464a4
Create Date: 2023-10-16 11:17:23.434073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532815d25eb1'
down_revision = 'c273e20464a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
