"""removed icon column

Revision ID: c273e20464a4
Revises: 16ebb5a28b00
Create Date: 2023-10-03 14:08:14.008508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c273e20464a4'
down_revision = '16ebb5a28b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pikmins', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pikmins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
